version: '3'

services:
  bot-dead-watcher-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      - DEAD_WATCHER_PORT=5503
      - TRADE_SERVER_URL=http://195.7.7.93:18080
    ports:
      - '5503:5503'
    networks:
      - app-dev-net
    restart: unless-stopped
    container_name: bot-dead-watcher-dev

  bot-dead-watcher-demo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      - DEAD_WATCHER_PORT=6503
      - TRADE_SERVER_URL=http://164.68.117.90:18080
    ports:
      - '6503:6503'
    networks:
      - app-demo-net
    restart: unless-stopped
    container_name: bot-dead-watcher-demo

networks:
  app-dev-net:
    driver: bridge
  app-demo-net:
    driver: bridge